[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
contract = "3jq9oBWGCUWmBynC8TTBL9KWJdGegsChJ1c8ksybGhum"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/contract.ts"
